name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set script permissions
        run: chmod +x ./scripts/build.sh

      - name: Run build
        run: ./scripts/build.sh
